import { PublicReviewForm } from "@/components/PublicReviewForm";
import { trpc } from "@/lib/trpc";
import { FM_HOMEBREW_KIND_META, normalizeHomebrewContent } from "@shared/fmHomebrew";
import { FM_ATTRIBUTE_LABELS } from "@shared/fmRules";
import { FM_MODIFIER_TARGET_LABELS, formatRequirement } from "@shared/fmCharacterState";
import type { FMTechnique } from "@shared/fmTypes";
import { BookOpen, Loader2, MoonStar, ShieldCheck, Sparkles } from "lucide-react";
import { useRoute } from "wouter";

function TechniqueReadOnly({ technique }: { technique: FMTechnique }) {
  return <><div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Fundamento e funcionamento</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-stone-300">{technique.basicFunction || "Sem descrição estruturada."}</p><p className="mt-5 font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Benefícios intrínsecos</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-stone-400">{technique.intrinsicBenefits || "Não informado."}</p><p className="mt-5 font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Limitações e contrajogo</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-stone-400">{technique.counterplay || technique.limitations || "Não informado."}</p></section><section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Características</p><dl className="mt-3 grid gap-4 text-sm"><div><dt className="text-stone-500">Atributos relacionados</dt><dd className="mt-2 flex flex-wrap gap-2">{technique.attributeKeys?.length ? technique.attributeKeys.map(attribute => <span key={attribute} className="rounded-md border border-amber-300/20 bg-amber-300/[.06] px-2 py-1 text-xs text-amber-100">{FM_ATTRIBUTE_LABELS[attribute]}</span>) : <span className="text-stone-400">Não informado</span>}</dd></div><div><dt className="text-stone-500">Itens necessários</dt><dd className="mt-1 whitespace-pre-wrap text-stone-300">{technique.requiredItems || "Não informado"}</dd></div><div><dt className="text-stone-500">Observações</dt><dd className="mt-1 whitespace-pre-wrap text-stone-300">{technique.reviewNotes || "Sem observações adicionais."}</dd></div></dl></section></div><section className="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.025] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-amber-300/70">Catálogo de poderes</p><h2 className="mt-1 font-display text-2xl text-stone-100">Poderes da Técnica</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{technique.powers?.length ? technique.powers.map(power => <article key={power.id} className="rounded-xl border border-violet-300/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><p className="font-medium text-amber-100">{power.name}</p><span className="text-xs text-stone-500">Nv. {power.requiredCharacterLevel}</span></div><p className="mt-2 text-xs uppercase tracking-[.12em] text-stone-500">{power.type} · poder {power.spellLevel}</p><p className="mt-3 text-sm leading-6 text-stone-300">{power.summary || "Sem descrição."}</p><p className="mt-3 text-xs leading-5 text-stone-500">Requisitos: {power.requirement || "Não informado"}</p></article>) : <p className="text-sm text-stone-500">Nenhum poder declarado.</p>}</div></section></>;
}

function HomebrewReadOnly({ shared }: { shared: { kind: string; content: Record<string, unknown> } }) {
  const content = normalizeHomebrewContent(shared.content);
  const meta = FM_HOMEBREW_KIND_META[shared.kind as keyof typeof FM_HOMEBREW_KIND_META];
  const fields = meta ? meta.fieldSpecs.map(field => ({ label: field.label, value: content.fields[field.key] ?? "" })) : Object.entries(content.fields).map(([label, value]) => ({ label, value }));
  return <><div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Funcionamento</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-stone-300">{content.description || "Sem descrição estruturada."}</p><p className="mt-5 font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Efeitos narrativos</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-stone-400">{content.effects || "Sem efeitos declarados."}</p></section><section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Requisitos e campos</p><dl className="mt-3 grid gap-3 text-sm"><div><dt className="text-stone-500">Requisitos narrativos</dt><dd className="mt-1 whitespace-pre-wrap text-stone-300">{content.requirements || "Não informado"}</dd></div><div><dt className="text-stone-500">Custo</dt><dd className="mt-1 text-stone-300">{content.cost || "Não informado"}</dd></div>{fields.map(field => <div key={field.label}><dt className="text-stone-500">{field.label}</dt><dd className="mt-1 whitespace-pre-wrap text-stone-300">{field.value || "Não informado"}</dd></div>)}</dl></section></div>{content.mechanics.modifiers.length || content.mechanics.requirements.length ? <section className="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.025] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-amber-300/70">Camada mecânica declarada</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[.14em] text-stone-500">Modificadores</p>{content.mechanics.modifiers.map(modifier => <p key={modifier.id} className="mt-2 text-sm text-stone-300"><strong className="text-amber-100">{FM_MODIFIER_TARGET_LABELS[modifier.target]}</strong> {modifier.value >= 0 ? "+" : ""}{modifier.value}</p>)}</div><div className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[.14em] text-stone-500">Requisitos mecânicos</p>{content.mechanics.requirements.map((requirement, index) => <p key={`${requirement.type}-${index}`} className="mt-2 text-sm text-stone-300">{formatRequirement(requirement)}</p>)}</div></div></section> : null}</>;
}

export default function PublicReview() {
  const [, params] = useRoute("/avaliar/:token");
  const token = params?.token ?? "";
  const contentQuery = trpc.reviews.getPublic.useQuery({ token }, { enabled: Boolean(token), retry: false });
  if (contentQuery.isLoading) return <div className="grid min-h-screen place-items-center bg-[#09060f] text-amber-300"><Loader2 className="h-8 w-8 animate-spin" /></div>;
  if (contentQuery.isError || !contentQuery.data) return <main className="grid min-h-screen place-items-center bg-[#09060f] px-5 text-center text-stone-100"><div><BookOpen className="mx-auto h-10 w-10 text-amber-300" /><h1 className="mt-5 font-display text-3xl">Conteúdo não encontrado</h1><p className="mt-3 max-w-md text-sm leading-6 text-stone-400">Este link de avaliação pode ter sido removido ou não está mais disponível.</p></div></main>;
  const shared = contentQuery.data;
  const technique = shared.targetType === "technique" ? shared.content as unknown as FMTechnique : null;
  const label = shared.targetType === "technique" ? technique?.kind === "martial" ? "Estilo Marcial" : "Técnica Amaldiçoada" : shared.targetType === "homebrew" ? FM_HOMEBREW_KIND_META[shared.kind as keyof typeof FM_HOMEBREW_KIND_META]?.label ?? "Homebrew" : "Ficha de personagem";
  return <main className="min-h-screen bg-[#09060f] px-4 py-7 text-stone-100 sm:px-6 sm:py-10"><div className="mx-auto max-w-5xl"><header className="rounded-2xl border border-amber-300/15 bg-[radial-gradient(circle_at_88%_10%,rgba(151,93,199,.18),transparent_36%),#120c1d] p-6 sm:p-8"><p className="flex items-center gap-2 font-display text-xs uppercase tracking-[.2em] text-amber-300/70"><MoonStar className="h-4 w-4" />Avaliação compartilhada · somente leitura</p><h1 className="mt-4 font-display text-4xl text-stone-100 sm:text-5xl">{shared.name}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-stone-400">{shared.summary}</p><span className="mt-4 inline-flex rounded-full border border-violet-300/20 bg-violet-500/10 px-3 py-1.5 text-xs text-violet-100">{label}</span></header><div className="mt-4">{technique ? <TechniqueReadOnly technique={technique} /> : shared.targetType === "homebrew" ? <HomebrewReadOnly shared={shared} /> : <div className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5 text-sm text-stone-400">A ficha compartilhada continua disponível para avaliação no formato existente.</div>}</div><div className="mt-4 rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-amber-300" /><p className="text-sm leading-6 text-stone-400">Você pode avaliar, comentar ou sugerir alterações, mas não pode modificar o conteúdo original. O proprietário decide se aceita, recusa ou implementa cada sugestão depois de editar a Técnica real.</p></div></div><div className="mt-4"><PublicReviewForm token={token} targetName={shared.name} /></div></div></main>;
}
