import type { FMAttributeKey, FMClanKey, FMOriginKey } from "./fmTypes";

export type FMAttributeAllocation = { total: number; maximumPerAttribute: number; allowedAttributes?: FMAttributeKey[]; requiredBonuses?: Partial<Record<"strength" | "dexterity" | "constitution", number>> };
export type FMOriginCatalogEntry = { id: Exclude<FMOriginKey, "custom">; name: string; description: string; creationNote: string; benefits: string[]; restrictions: string[]; attributeAllocation: FMAttributeAllocation; rare?: boolean; requiresRestrictedSpecialization?: boolean };
export type FMClanCatalogEntry = { id: Exclude<FMClanKey, "custom">; name: string; description: string; creationNote: string; benefits: string[]; restrictions: string[]; trainedSkills: string[]; inheritedTechniques: string[]; attributeAllocation: FMAttributeAllocation };

export const FM_ORIGIN_CATALOG: FMOriginCatalogEntry[] = [
  { id: "innate", name: "Inato", description: "Afinidade natural com energia amaldiçoada e técnica própria em desenvolvimento.", creationNote: "Distribua +2 em um atributo e +1 em outro; escolha características de origem com a mesa.", benefits: ["Técnica Inata", "Talento Natural"], restrictions: [], attributeAllocation: { total: 3, maximumPerAttribute: 2 } },
  { id: "inherited", name: "Herdado", description: "Poder herdado de uma linhagem ou clã, com técnica e treinamentos associados.", creationNote: "Escolha também um clã; os bônus e treinamentos dependem da herança escolhida.", benefits: ["Técnica Herdada", "Treinamentos de Clã"], restrictions: ["Exige clã ou linhagem selecionada."], attributeAllocation: { total: 0, maximumPerAttribute: 0 } },
  { id: "derived", name: "Derivado", description: "Energia oriunda de uma fonte anormal, com desenvolvimento concentrado e singular.", creationNote: "Distribua +2 em um atributo e +1 em outro; registre a fonte da derivação.", benefits: ["Energia Antinatural", "Foco de Derivação"], restrictions: ["Origem rara; depende de aprovação da campanha."], attributeAllocation: { total: 3, maximumPerAttribute: 2 }, rare: true },
  { id: "restricted", name: "Restringido", description: "Pessoa marcada por Restrição Celeste, focada em físico, combate e armas.", creationNote: "Aumente Força, Destreza e Constituição em +1 e distribua 2 pontos físicos; exige Especialização Restringido.", benefits: ["Restrição Celeste", "Aprimoramento Físico"], restrictions: ["Exige Especialização Restringido."], attributeAllocation: { total: 5, maximumPerAttribute: 3, requiredBonuses: { strength: 1, dexterity: 1, constitution: 1 } }, rare: true, requiresRestrictedSpecialization: true },
  { id: "cursed-womb", name: "Feto Amaldiçoado Híbrido", description: "Existência híbrida de humano e maldição, com natureza e progressão próprias.", creationNote: "Distribua +2 em um atributo e +1 em outro; defina herança e efeitos com aprovação da mesa.", benefits: ["Herança Maldita", "Anatomia Híbrida"], restrictions: ["Origem rara; exige aprovação da mesa."], attributeAllocation: { total: 3, maximumPerAttribute: 2 }, rare: true },
  { id: "technique-less", name: "Sem Técnica", description: "Feiticeiro sem técnica inata, dedicado a estudo, perícias, armas e jujutsus alternativos.", creationNote: "Distribua 4 pontos entre atributos, máximo de +3 no mesmo atributo; não recebe técnica nem feitiços.", benefits: ["Estudos Dedicados", "Foco Marcial ou de Ofício"], restrictions: ["Não possui Técnica Inata ou Feitiços.", "Não pode ser Especialista em Técnica."], attributeAllocation: { total: 4, maximumPerAttribute: 3 } },
  { id: "mutant-cursed-corpse", name: "Corpo Amaldiçoado Mutante", description: "Forma de vida sintética com anatomia e núcleos próprios.", creationNote: "Distribua 2 pontos de atributo e descreva a forma de vida sintética com o mestre.", benefits: ["Forma de Vida Sintética", "Núcleos Amaldiçoados"], restrictions: ["Origem rara; anatomia definida com a mesa."], attributeAllocation: { total: 2, maximumPerAttribute: 2 }, rare: true },
];

export const FM_CLAN_CATALOG: FMClanCatalogEntry[] = [
  { id: "gojo", name: "Clã Gojo", description: "Herança ligada aos Seis Olhos e ao Ilimitado, voltada ao estudo e ao desenvolvimento de feitiços.", creationNote: "Distribua +2 entre Inteligência e Sabedoria e +1 no outro atributo. Escolha dois treinamentos entre Feitiçaria, Percepção e Intuição, ou especialize-se em um.", benefits: ["Potencial Lendário: +1 PE em todo nível par.", "Feitiço adicional no nível 1 e nos níveis 5, 10, 15 e 20."], restrictions: ["Requer Origem Herdado para receber os benefícios."], trainedSkills: ["Feitiçaria", "Percepção", "Intuição"], inheritedTechniques: ["Seis Olhos", "Ilimitado"], attributeAllocation: { total: 3, maximumPerAttribute: 2, allowedAttributes: ["intelligence", "wisdom"] } },
  { id: "inumaki", name: "Clã Inumaki", description: "Linhagem menor cuja herança manifesta a Fala Amaldiçoada e marcas ritualísticas próprias.", creationNote: "Distribua +2 entre Inteligência e Presença e +1 no outro atributo. Escolha dois treinamentos entre Feitiçaria, Percepção e Intuição, ou especialize-se em um.", benefits: ["Olhos de Cobra e Presas: um número de vezes igual ao bônus de treinamento, comande uma ação bônus de aliado como reação.", "Recupera os usos após descanso longo."], restrictions: ["Requer Origem Herdado para receber os benefícios."], trainedSkills: ["Feitiçaria", "Percepção", "Intuição"], inheritedTechniques: ["Fala Amaldiçoada"], attributeAllocation: { total: 3, maximumPerAttribute: 2, allowedAttributes: ["intelligence", "presence"] } },
  { id: "kamo", name: "Clã Kamo", description: "Herança de Manipulação Sanguínea que valoriza vitalidade, sangue e aprimoramento físico controlado.", creationNote: "Distribua +2 entre Constituição e Sabedoria e +1 no outro atributo. Escolha dois treinamentos entre Atletismo, Medicina e Persuasão, ou especialize-se em um.", benefits: ["Valor do Sangue: +1 PV máximo adicional a cada nível.", "No nível 10, some o modificador de Constituição ao total de PV; em rolagens de PV abaixo da média, role novamente e fique com o maior."], restrictions: ["Requer Origem Herdado para receber os benefícios."], trainedSkills: ["Atletismo", "Medicina", "Persuasão"], inheritedTechniques: ["Manipulação Sanguínea"], attributeAllocation: { total: 3, maximumPerAttribute: 2, allowedAttributes: ["constitution", "wisdom"] } },
  { id: "zenin", name: "Clã Zenin", description: "Clã maior dedicado ao poder e ao potencial das técnicas herdadas, incluindo Dez Sombras e Projeção.", creationNote: "Aumente um atributo em +2 e outro em +1. Escolha quaisquer duas perícias para treinamento ou especialize-se em uma.", benefits: ["Foco no Poder: escolha um Feitiço Focado no nível 1 e outro nos níveis 5, 10, 15 e 20.", "Um Feitiço Focado amplia dano, cura, alcance ou CD de resistência conforme o livro."], restrictions: ["Requer Origem Herdado para receber os benefícios."], trainedSkills: ["Quaisquer duas perícias"], inheritedTechniques: ["Dez Sombras", "Projeção"], attributeAllocation: { total: 3, maximumPerAttribute: 2 } },
];

export function getOriginCatalogEntry(id: FMOriginKey) { return FM_ORIGIN_CATALOG.find(origin => origin.id === id) ?? null; }
export function getClanCatalogEntry(id: FMClanKey) { return FM_CLAN_CATALOG.find(clan => clan.id === id) ?? null; }
export function resolveClanId(value: unknown, clanName?: unknown): FMClanKey {
  if (typeof value === "string" && (value === "custom" || FM_CLAN_CATALOG.some(clan => clan.id === value))) return value as FMClanKey;
  if (typeof clanName !== "string") return "custom";
  const normalized = clanName.trim().toLocaleLowerCase("pt-BR").replace(/^clã\s+/, "");
  return FM_CLAN_CATALOG.find(clan => clan.id === normalized || clan.name.toLocaleLowerCase("pt-BR").replace(/^clã\s+/, "") === normalized)?.id ?? "custom";
}
export function getOriginAttributeAllocation(originId: FMOriginKey, clanId: FMClanKey) { return originId === "inherited" ? getClanCatalogEntry(clanId)?.attributeAllocation ?? getOriginCatalogEntry(originId)?.attributeAllocation ?? null : getOriginCatalogEntry(originId)?.attributeAllocation ?? null; }
