import { EditableObservation } from "@/components/EditableObservation";
import type { FMCharacterSheet, FMObservationEntityType } from "@shared/fmTypes";

type UpdateSheet = (updater: (current: FMCharacterSheet) => FMCharacterSheet) => void;
type AddDiary = (title: string, detail: string, category?: FMCharacterSheet["diary"][number]["category"]) => void;
type Entry = { entityType: FMObservationEntityType; id: string; title: string; value: string; placeholder: string; save: (value: string) => void };

export function CharacterObservationsPanel({ sheet, onUpdate, onDiary }: { sheet: FMCharacterSheet; onUpdate: UpdateSheet; onDiary: AddDiary }) {
  const record = (title: string, detail: string) => onDiary("Observação atualizada", `${title}: ${detail || "observação removida"}`, "note");
  const entries: Entry[] = [
    { entityType: "technique", id: "technique", title: sheet.technique.name || "Técnica Amaldiçoada", value: sheet.technique.notes ?? "", placeholder: "Registre uma observação breve sobre a técnica.", save: value => onUpdate(current => ({ ...current, technique: { ...current.technique, notes: value } })) },
    ...sheet.aptitudes.map(item => ({ entityType: "aptitude" as const, id: item.id, title: `Aptidão · ${item.name}`, value: item.notes ?? "", placeholder: "Registre uma observação sobre esta aptidão.", save: (value: string) => onUpdate(current => ({ ...current, aptitudes: current.aptitudes.map(entry => entry.id === item.id ? { ...entry, notes: value } : entry) })) })),
    ...sheet.training.map(item => ({ entityType: "training" as const, id: item.trackId, title: `Treinamento · ${item.label ?? item.trackId}`, value: item.notes ?? "", placeholder: "Registre um objetivo ou anotação de treinamento.", save: (value: string) => onUpdate(current => ({ ...current, training: current.training.map(entry => entry.trackId === item.trackId ? { ...entry, notes: value } : entry) })) })),
    ...sheet.invocations.map(item => ({ entityType: "invocation" as const, id: item.id, title: `Invocação · ${item.name}`, value: item.notes ?? "", placeholder: "Registre uma observação sobre esta invocação.", save: (value: string) => onUpdate(current => ({ ...current, invocations: current.invocations.map(entry => entry.id === item.id ? { ...entry, notes: value } : entry) })) })),
    ...sheet.equipment.map(item => ({ entityType: "equipment" as const, id: item.id, title: `Equipamento · ${item.name}`, value: item.notes ?? "", placeholder: "Registre uma observação sobre este equipamento.", save: (value: string) => onUpdate(current => ({ ...current, equipment: current.equipment.map(entry => entry.id === item.id ? { ...entry, notes: value } : entry) })) })),
    ...sheet.cursedTools.map(item => ({ entityType: "equipment" as const, id: item.id, title: `Ferramenta Amaldiçoada · ${item.name}`, value: item.notes ?? "", placeholder: "Registre uma observação sobre esta ferramenta.", save: (value: string) => onUpdate(current => ({ ...current, cursedTools: current.cursedTools.map(entry => entry.id === item.id ? { ...entry, notes: value } : entry) })) })),
    ...sheet.allies.map(item => ({ entityType: "ally" as const, id: item.id, title: `Aliado · ${item.name}`, value: item.notes ?? "", placeholder: "Registre uma observação sobre este aliado.", save: (value: string) => onUpdate(current => ({ ...current, allies: current.allies.map(entry => entry.id === item.id ? { ...entry, notes: value } : entry) })) })),
  ];
  if (sheet.domainExpansion) entries.push({ entityType: "domain", id: "domain-expansion", title: `Domínio · ${sheet.domainExpansion.name || "sem nome"}`, value: sheet.domainExpansion.notes ?? "", placeholder: "Registre decisões de mesa, riscos ou detalhes narrativos deste Domínio.", save: value => onUpdate(current => ({ ...current, domainExpansion: current.domainExpansion ? { ...current.domainExpansion, notes: value } : current.domainExpansion })) });
  return <section className="mt-4 rounded-2xl border border-violet-300/12 bg-[#120c1d]/85 p-4 sm:p-5"><div className="border-b border-violet-300/10 pb-4"><p className="font-display text-[11px] uppercase tracking-[.2em] text-amber-300/70">Registro rápido</p><h3 className="mt-1 font-display text-xl text-stone-100">Observações das entidades</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-stone-400">Adicione ou ajuste notas curtas sem abrir o editor completo de cada entidade. O salvamento usa a própria ficha e cria um registro no Diário.</p></div><div className="mt-4 grid gap-3 xl:grid-cols-2">{entries.map(entry => <EditableObservation key={`${entry.entityType}:${entry.id}`} entityType={entry.entityType} entityId={entry.id} value={entry.value} canEdit onSave={value => { entry.save(value); record(entry.title, value); }} label={entry.title} placeholder={entry.placeholder} />)}</div></section>;
}
