import React from "react";
import { FM_ATTRIBUTE_LABELS, getDerivedValues, getResourceLabel } from "@shared/fmRules";
import { fmAttributeKeys, type FMCharacterSheet } from "@shared/fmTypes";
import { FM_INVOCATION_TYPE_LABELS, getInvocationDerived } from "@shared/fmInvocations";
import { hydrateSheet } from "@shared/fmSheetHydration";

export function CharacterReviewPreview({ content }: { content: unknown }) {
  const sheet = hydrateSheet(content as Partial<FMCharacterSheet>);
  const derived = getDerivedValues(sheet);
  const resourceLabel = getResourceLabel(sheet.progression.specialization, sheet.progression.nonSorcerer);
  const spells = sheet.spells.slice(0, 4);
  const invocations = sheet.invocations.slice(0, 4);

  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {[
        ["Pontos de Vida", `${sheet.resources.health.current}/${derived.healthMaximum}`],
        [resourceLabel, `${sheet.resources.energy.current}/${derived.energyMaximum}`],
        ["Defesa", String(derived.defense)],
        ["Iniciativa", `${derived.initiative >= 0 ? "+" : ""}${derived.initiative}`],
      ].map(([label, value]) => <article key={label} className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-4"><p className="font-display text-xs uppercase tracking-[.16em] text-violet-200/70">{label}</p><p className="mt-3 font-display text-3xl text-amber-200">{value}</p></article>)}
    </section>

    <div className="mt-4 grid gap-4 xl:grid-cols-2">
      <section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Identidade e capacidades</p><h2 className="mt-2 font-display text-2xl text-stone-100">{sheet.identity.name || "Personagem sem nome"}</h2><p className="mt-2 text-sm text-stone-400">{sheet.identity.player || "Jogador não informado"}{sheet.identity.grade ? ` · ${sheet.identity.grade}` : ""}{sheet.origin.name ? ` · ${sheet.origin.name}` : ""}</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{fmAttributeKeys.map(attribute => <div key={attribute} className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[.12em] text-stone-500">{FM_ATTRIBUTE_LABELS[attribute]}</p><p className="mt-1 font-display text-2xl text-amber-200">{derived.attributes[attribute]}</p></div>)}</div><div className="mt-5 rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[.12em] text-stone-500">Técnica amaldiçoada</p><p className="mt-1 font-medium text-amber-100">{sheet.technique.name || "Não informada"}</p><p className="mt-2 text-sm leading-6 text-stone-400">{sheet.technique.basicFunction || "Sem funcionamento básico registrado."}</p></div></section>
      <section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Sobrevivência e cena</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[.12em] text-stone-500">Testes de Morte</p><p className="mt-2 text-sm text-emerald-200">{sheet.deathSaves?.successes ?? 0} sucesso(s)</p><p className="mt-1 text-sm text-rose-200">{sheet.deathSaves?.failures ?? 0} fracasso(s)</p><p className="mt-2 text-xs text-stone-500">{sheet.deathSaves?.stabilized ? "Estabilizado" : "Em acompanhamento"}</p></div><div className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[.12em] text-stone-500">Recursos</p><p className="mt-2 text-sm text-amber-200">Inspiração: {sheet.inspiration ?? 1}</p><p className="mt-1 text-sm text-stone-300">Limite de energia: {sheet.energyLimit ?? 999999}</p></div></div><div className="mt-3 rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[.12em] text-stone-500">Resistências e reduções</p><p className="mt-2 text-sm text-stone-300">{sheet.resistances?.filter(Boolean).join(" · ") || "Nenhuma resistência declarada"}</p><p className="mt-2 text-xs text-rose-200">Vulnerabilidades: {sheet.vulnerabilities?.filter(Boolean).join(" · ") || "Nenhuma"}</p>{sheet.damageReductions?.length ? <div className="mt-3 flex flex-wrap gap-2">{sheet.damageReductions.map(reduction => <span key={reduction.id} className="rounded-md border border-violet-300/10 px-2 py-1 text-xs text-stone-300">RD {reduction.damageType}: {reduction.amount}</span>)}</div> : null}</div></section>
    </div>

    <div className="mt-4 grid gap-4 xl:grid-cols-2">
      <section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Magias e Invocações</p><div className="mt-4 space-y-3">{spells.map(spell => <div key={spell.id} className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="font-medium text-stone-200">{spell.name}</p><p className="mt-1 text-xs text-stone-500">Nível {spell.level} · {spell.effect || "Sem efeito registrado"}</p></div>)}{invocations.map(invocation => { const values = getInvocationDerived(invocation, sheet.progression.level, derived.trainingBonus); return <div key={invocation.id} className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="font-medium text-stone-200">{invocation.name || "Invocação sem nome"}</p><p className="mt-1 text-xs text-amber-200">{FM_INVOCATION_TYPE_LABELS[invocation.type ?? "shikigami"]} · PV {values.health} · Defesa {values.defense} · custo {values.totalSummonCost}</p></div>; })}{!spells.length && !invocations.length ? <p className="text-sm text-stone-500">Nenhuma Magia, Maldição ou Invocação declarada.</p> : null}</div></section>
      <section className="rounded-2xl border border-violet-300/10 bg-[#120c1d] p-5"><p className="font-display text-xs uppercase tracking-[.18em] text-violet-200/70">Desenvolvimento</p><div className="mt-4 space-y-3">{sheet.aptitudes.slice(0, 4).map(aptitude => <div key={aptitude.id} className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="font-medium text-stone-200">{aptitude.name}</p><p className="mt-1 text-xs text-stone-500">{aptitude.description || aptitude.effect || "Sem descrição."}</p></div>)}{sheet.training.slice(0, 4).map(training => <div key={training.trackId} className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><p className="font-medium text-stone-200">{training.label || training.trackId} <span className="text-xs font-normal text-amber-200">· etapa {training.stage}/4</span></p><p className="mt-1 text-xs text-stone-500">{training.notes || training.effect || training.stageEffects?.[training.stage as 1 | 2 | 3 | 4]?.description || "Sem descrição."}</p></div>)}{!sheet.aptitudes.length && !sheet.training.length ? <p className="text-sm text-stone-500">Nenhuma Aptidão ou Treinamento declarado.</p> : null}</div></section>
    </div>
  </>;
}
