import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { FMCharacterSheet, FMDamageReduction } from "@shared/fmTypes";
import { Minus, Plus, RotateCcw, ShieldAlert, Skull } from "lucide-react";

type UpdateSheet = (updater: (current: FMCharacterSheet) => FMCharacterSheet) => void;
type AddDiary = (title: string, detail: string, category?: FMCharacterSheet["diary"][number]["category"]) => void;

const DAMAGE_TYPES = ["Cortante", "Perfurante", "Impacto", "Ácido", "Chocante", "Congelante", "Energia Reversa", "Sônico", "Necrótico", "Psíquico", "Queimante", "Radiante", "Venenoso", "Dano na alma", "RD Geral"] as const;
const baseInput = "border-violet-300/15 bg-[#0b0711] text-stone-100 placeholder:text-stone-600";

function Counter({ value, onChange, label }: { value: number; onChange: (value: number) => void; label: string }) {
  return <div className="flex items-center gap-2" aria-label={label}><Button type="button" size="icon" variant="outline" onClick={() => onChange(Math.max(0, value - 1))} className="border-violet-300/15" aria-label={`Diminuir ${label}`}><Minus className="h-4 w-4" /></Button><span className="min-w-8 text-center font-display text-xl text-amber-100">{value}</span><Button type="button" size="icon" variant="outline" onClick={() => onChange(value + 1)} className="border-violet-300/15" aria-label={`Aumentar ${label}`}><Plus className="h-4 w-4" /></Button></div>;
}

export function CombatResiliencePanel({ sheet, updateSheet, addDiary }: { sheet: FMCharacterSheet; updateSheet: UpdateSheet; addDiary: AddDiary }) {
  const death = sheet.deathSaves ?? { successes: 0, failures: 0, stabilized: false, notes: "" };
  const reductions = sheet.damageReductions ?? [];
  const resistances = sheet.resistances ?? [];
  const vulnerabilities = sheet.vulnerabilities ?? [];
  const setDeath = (patch: Partial<typeof death>) => updateSheet(current => ({ ...current, deathSaves: { ...(current.deathSaves ?? death), ...patch } }));
  const updateReduction = (id: string, patch: Partial<FMDamageReduction>) => updateSheet(current => ({ ...current, damageReductions: (current.damageReductions ?? []).map(item => item.id === id ? { ...item, ...patch } : item) }));
  const removeReduction = (id: string) => updateSheet(current => ({ ...current, damageReductions: (current.damageReductions ?? []).filter(item => item.id !== id) }));
  const addReduction = (damageType: string) => updateSheet(current => ({ ...current, damageReductions: [...(current.damageReductions ?? []), { id: crypto.randomUUID(), damageType, amount: 0, notes: "" }] }));
  const updateStringList = (field: "resistances" | "vulnerabilities", index: number, value: string) => updateSheet(current => ({ ...current, [field]: (current[field] ?? []).map((item, itemIndex) => itemIndex === index ? value : item) }));
  const addStringList = (field: "resistances" | "vulnerabilities") => updateSheet(current => ({ ...current, [field]: [...(current[field] ?? []), ""] }));
  const removeStringList = (field: "resistances" | "vulnerabilities", index: number) => updateSheet(current => ({ ...current, [field]: (current[field] ?? []).filter((_, itemIndex) => itemIndex !== index) }));
  const resetDeath = () => { setDeath({ successes: 0, failures: 0, stabilized: false }); addDiary("Testes de Morte reiniciados", "Sucessos e fracassos voltaram a zero.", "combat"); };
  return <div className="mt-4 space-y-4">
    <section className="rounded-2xl border border-violet-300/10 bg-[#120c1d]/80 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-display text-xs uppercase tracking-[.18em] text-amber-300/70">Sobrevivência</p><h3 className="mt-1 font-display text-xl text-stone-100">Testes de Morte</h3><p className="mt-1 text-sm leading-6 text-stone-400">Registre os sucessos e fracassos da cena. O estado fica salvo na ficha e as alterações importantes entram no Diário.</p></div><Button type="button" size="sm" variant="outline" onClick={resetDeath}><RotateCcw className="mr-2 h-4 w-4" />Reiniciar</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.04] p-4"><p className="text-xs uppercase tracking-[.14em] text-emerald-200/75">Sucessos</p><div className="mt-2 flex items-center justify-between gap-3"><Counter value={death.successes} label="sucessos" onChange={value => { setDeath({ successes: value }); addDiary("Teste de Morte — sucesso", `Total de sucessos: ${value}.`, "combat"); }} /><span className="text-xs text-stone-500">3 estabiliza</span></div></div><div className="rounded-xl border border-rose-300/15 bg-rose-300/[.04] p-4"><p className="text-xs uppercase tracking-[.14em] text-rose-200/75">Fracassos</p><div className="mt-2 flex items-center justify-between gap-3"><Counter value={death.failures} label="fracassos" onChange={value => { setDeath({ failures: value }); addDiary("Teste de Morte — fracasso", `Total de fracassos: ${value}.`, "combat"); }} /><span className="text-xs text-stone-500">3 agrava</span></div></div><div className="rounded-xl border border-violet-300/15 bg-black/20 p-4"><p className="text-xs uppercase tracking-[.14em] text-stone-500">Estado</p><div className="mt-2 flex items-center gap-2 text-sm text-stone-200"><Skull className="h-4 w-4 text-amber-200" />{death.stabilized ? "Estabilizado" : death.successes >= 3 ? "Estável" : death.failures >= 3 ? "Morto ou agravado" : "Em risco"}</div><label className="mt-3 flex items-center gap-2 text-xs text-stone-400"><input type="checkbox" className="accent-amber-300" checked={death.stabilized} onChange={event => setDeath({ stabilized: event.target.checked })} /> Estabilizado manualmente</label></div></div><div className="mt-3"><label className="grid gap-1.5 text-sm font-medium text-stone-300"><span>Observações do teste</span><Textarea value={death.notes} onChange={event => setDeath({ notes: event.target.value })} className={baseInput} placeholder="Condições, ajuda recebida ou resultado narrativo." /></label></div></section>
    <section className="rounded-2xl border border-violet-300/10 bg-[#120c1d]/80 p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-display text-xs uppercase tracking-[.18em] text-amber-300/70">Mitigação</p><h3 className="mt-1 font-display text-xl text-stone-100">Reduções de Dano</h3><p className="mt-1 text-sm leading-6 text-stone-400">Quantidade reduzida por tipo de dano. RD Geral pode ser usada como redução universal.</p></div><select className={`h-10 rounded-md px-3 text-sm ${baseInput}`} value="" onChange={event => { if (event.target.value) addReduction(event.target.value); }} aria-label="Adicionar tipo de redução"><option value="">Adicionar tipo</option>{DAMAGE_TYPES.map(type => <option key={type} value={type}>{type}</option>)}</select></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{reductions.map(reduction => <div key={reduction.id} className="rounded-xl border border-violet-300/10 bg-black/20 p-3"><div className="grid grid-cols-[1fr_76px_auto] items-end gap-2"><label className="grid gap-1.5 text-xs font-medium text-stone-400"><span>Tipo</span><select value={reduction.damageType} onChange={event => updateReduction(reduction.id, { damageType: event.target.value })} className={`h-10 rounded-md px-2 text-sm ${baseInput}`}>{DAMAGE_TYPES.map(type => <option key={type} value={type}>{type}</option>)}</select></label><label className="grid gap-1.5 text-xs font-medium text-stone-400"><span>Quantidade</span><Input type="number" min={0} value={reduction.amount} onChange={event => updateReduction(reduction.id, { amount: Math.max(0, Number(event.target.value) || 0) })} className={baseInput} /></label><Button type="button" size="icon" variant="outline" onClick={() => removeReduction(reduction.id)} aria-label={`Remover redução de ${reduction.damageType}`}><Minus className="h-4 w-4" /></Button></div><Input value={reduction.notes} onChange={event => updateReduction(reduction.id, { notes: event.target.value })} placeholder="Fonte ou observação" className={`mt-2 ${baseInput}`} /></div>)}{reductions.length === 0 ? <p className="text-sm text-stone-500 md:col-span-2 xl:col-span-3">Nenhuma redução específica registrada.</p> : null}</div></section>
    <section className="grid gap-4 xl:grid-cols-2"><EditableList title="Resistências" icon={<ShieldAlert className="h-4 w-4" />} values={resistances} field="resistances" onAdd={addStringList} onUpdate={updateStringList} onRemove={removeStringList} /><EditableList title="Vulnerabilidades" icon={<ShieldAlert className="h-4 w-4" />} values={vulnerabilities} field="vulnerabilities" onAdd={addStringList} onUpdate={updateStringList} onRemove={removeStringList} /></section>
    <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-violet-300/10 bg-[#120c1d]/80 p-4"><p className="text-xs uppercase tracking-[.14em] text-stone-500">Inspiração</p><Input type="number" min={0} value={sheet.inspiration ?? 1} onChange={event => updateSheet(current => ({ ...current, inspiration: Math.max(0, Number(event.target.value) || 0) }))} className={`mt-2 ${baseInput}`} /><p className="mt-2 text-xs text-stone-500">Marcadores disponíveis para a cena.</p></div><div className="rounded-2xl border border-violet-300/10 bg-[#120c1d]/80 p-4"><p className="text-xs uppercase tracking-[.14em] text-stone-500">Limite de Energia</p><Input type="number" min={0} value={sheet.energyLimit ?? 999999} onChange={event => updateSheet(current => ({ ...current, energyLimit: Math.max(0, Number(event.target.value) || 0) }))} className={`mt-2 ${baseInput}`} /><p className="mt-2 text-xs text-stone-500">Limite de campanha; o cálculo normal de energia continua separado.</p></div></section>
  </div>;
}

function EditableList({ title, icon, values, field, onAdd, onUpdate, onRemove }: { title: string; icon: React.ReactNode; values: string[]; field: "resistances" | "vulnerabilities"; onAdd: (field: "resistances" | "vulnerabilities") => void; onUpdate: (field: "resistances" | "vulnerabilities", index: number, value: string) => void; onRemove: (field: "resistances" | "vulnerabilities", index: number) => void }) {
  return <section className="rounded-2xl border border-violet-300/10 bg-[#120c1d]/80 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><h3 className="flex items-center gap-2 font-display text-xl text-stone-100">{icon}{title}</h3><Button type="button" size="sm" variant="outline" onClick={() => onAdd(field)}><Plus className="mr-2 h-4 w-4" />Adicionar</Button></div><div className="mt-4 space-y-2">{values.map((value, index) => <div key={`${field}-${index}`} className="flex items-center gap-2"><Input value={value} onChange={event => onUpdate(field, index, event.target.value)} className={baseInput} placeholder={`Descreva ${title.toLocaleLowerCase("pt-BR")}`} /><Button type="button" size="icon" variant="outline" onClick={() => onRemove(field, index)} aria-label={`Remover ${title}`}><Minus className="h-4 w-4" /></Button></div>)}{values.length === 0 ? <p className="text-sm text-stone-500">Nenhum registro. Adicione uma linha para descrever a regra.</p> : null}</div></section>;
}
