import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CheckCircle2, Shield, Trash2 } from "lucide-react";
import type { FMCharacterSheet, FMDomainExpansion } from "@shared/fmTypes";
import { EditableObservation } from "./EditableObservation";

type UpdateSheet = (updater: (current: FMCharacterSheet) => FMCharacterSheet) => void;
type AddDiary = (title: string, detail: string, category?: FMCharacterSheet["diary"][number]["category"]) => void;

const blankDomain = (): FMDomainExpansion => ({ name: "", type: "simple", requiredLevel: 6, energyCost: 0, barrierHealth: 0, barrierResilience: 0, guaranteedHit: false, maximumTechnique: "", effect: "", counterplay: "", approved: false });
const fieldStyle = "border-violet-300/15 bg-[#0b0711] text-stone-100 placeholder:text-stone-600 focus-visible:border-amber-300/45";

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return <label className="grid gap-1.5 rounded-xl border border-transparent p-1 text-sm text-stone-300 transition-colors focus-within:border-violet-300/15 focus-within:bg-violet-300/[.025]"><span className="text-[11px] font-medium uppercase tracking-[.13em] text-stone-400">{label}</span>{children}{hint ? <span className="text-xs leading-5 text-stone-500">{hint}</span> : null}</label>;
}

function StatusCard({ label, value, tone = "violet" }: { label: string; value: string | number; tone?: "violet" | "amber" | "emerald" }) {
  const tones = { violet: "border-violet-300/15 bg-violet-300/[.035] text-violet-100", amber: "border-amber-300/15 bg-amber-300/[.035] text-amber-100", emerald: "border-emerald-300/15 bg-emerald-300/[.035] text-emerald-100" };
  return <div className={`rounded-xl border p-3 ${tones[tone]}`}><p className="text-[10px] uppercase tracking-[.15em] text-stone-500">{label}</p><p className="mt-1 font-display text-lg">{value}</p></div>;
}

export function DomainExpansionPanel({ sheet, onUpdate, onDiary }: { sheet: FMCharacterSheet; onUpdate: UpdateSheet; onDiary: AddDiary }) {
  const domain = sheet.domainExpansion;
  const update = (patch: Partial<FMDomainExpansion>) => onUpdate(current => ({ ...current, domainExpansion: { ...(current.domainExpansion ?? blankDomain()), ...patch } }));
  if (!domain) return <div className="space-y-5"><header className="rounded-2xl border border-violet-300/12 bg-[linear-gradient(120deg,rgba(86,43,121,.14),rgba(12,7,19,.92)_55%)] p-5 sm:p-6"><p className="text-xs uppercase tracking-[.22em] text-amber-300/75">Capacidades · registro avançado</p><h2 className="mt-2 font-display text-3xl text-stone-100">Domínio e expansão</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-400">Crie este registro somente quando a expansão existir na campanha. Custo, barreira, efeito, contrajogo e aprovação permanecerão explícitos.</p><Button type="button" onClick={() => { onUpdate(current => ({ ...current, domainExpansion: blankDomain() })); onDiary("Domínio iniciado", "Um registro de Domínio/Expansão foi criado para revisão.", "note"); }} className="mt-5 bg-amber-300 text-[#190d07] hover:bg-amber-200"><Shield className="mr-2 h-4 w-4" />Criar registro de domínio</Button></header><section className="rounded-2xl border border-dashed border-violet-300/15 bg-black/20 p-6 text-center text-sm leading-6 text-stone-500">O personagem não possui uma expansão registrada. Este espaço permanece vazio até a mesa definir uma capacidade aplicável.</section></div>;
  const status = domain.approved ? "Aprovada" : "Aguardando aprovação";
  return <div className="space-y-5"><header className="rounded-2xl border border-violet-300/12 bg-[linear-gradient(120deg,rgba(86,43,121,.14),rgba(12,7,19,.92)_55%)] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-amber-300/75">Capacidades · registro avançado</p><h2 className="mt-2 font-display text-3xl text-stone-100">Domínio e expansão</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-400">Organize os dados de cena em quatro etapas, mantendo o registro separado da Técnica Amaldiçoada.</p></div><Button type="button" variant="outline" onClick={() => { onUpdate(current => ({ ...current, domainExpansion: null })); onDiary("Domínio removido", "O registro de Domínio/Expansão foi removido.", "note"); }} className="border-rose-400/30 text-rose-200 hover:bg-rose-950/40"><Trash2 className="mr-2 h-4 w-4" />Remover registro</Button></div><div className="mt-5 grid gap-2 sm:grid-cols-3"><StatusCard label="Registro" value={domain.type === "simple" ? "Domínio simples" : "Expansão"} /><StatusCard label="Custo" value={`${domain.energyCost} PE`} tone="amber" /><StatusCard label="Mesa" value={status} tone={domain.approved ? "emerald" : "violet"} /></div></header>
    <section className="rounded-2xl border border-violet-300/12 bg-[#120c1d]/85 p-4 sm:p-5"><div className="flex items-center gap-3 border-b border-violet-300/10 pb-4"><span className="grid h-7 w-7 place-items-center rounded-full border border-amber-300/25 bg-amber-300/[.06] text-xs font-semibold text-amber-100">1</span><div><h3 className="font-display text-xl text-stone-100">Identidade e custo</h3><p className="mt-1 text-sm text-stone-500">Defina como a expansão é conhecida e quando pode ser acessada.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field label="Nome da expansão"><Input value={domain.name} onChange={event => update({ name: event.target.value })} placeholder="Ex.: Jardim das Sombras" className={fieldStyle} /></Field><Field label="Tipo"><select value={domain.type} onChange={event => update({ type: event.target.value as FMDomainExpansion["type"] })} className={`h-10 rounded-md px-3 text-sm ${fieldStyle}`}><option value="simple">Domínio simples</option><option value="incomplete">Expansão incompleta</option><option value="complete">Expansão completa</option><option value="barrierless">Sem barreiras</option></select></Field><Field label="Nível necessário"><Input type="number" min={1} max={30} value={domain.requiredLevel} onChange={event => update({ requiredLevel: Math.max(1, Number(event.target.value) || 1) })} className={fieldStyle} /></Field><Field label="Custo de energia"><Input type="number" min={0} value={domain.energyCost} onChange={event => update({ energyCost: Math.max(0, Number(event.target.value) || 0) })} className={fieldStyle} /></Field></div></section>
    <section className="rounded-2xl border border-violet-300/12 bg-[#120c1d]/85 p-4 sm:p-5"><div className="flex items-center gap-3 border-b border-violet-300/10 pb-4"><span className="grid h-7 w-7 place-items-center rounded-full border border-violet-300/25 bg-violet-300/[.06] text-xs font-semibold text-violet-100">2</span><div><h3 className="font-display text-xl text-stone-100">Barreira e vínculo</h3><p className="mt-1 text-sm text-stone-500">Registre resistência e relação com uma técnica máxima sem misturar estes valores ao efeito.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label="Vida da barreira"><Input type="number" min={0} value={domain.barrierHealth} onChange={event => update({ barrierHealth: Math.max(0, Number(event.target.value) || 0) })} className={fieldStyle} /></Field><Field label="Resistência da barreira"><Input type="number" min={0} value={domain.barrierResilience} onChange={event => update({ barrierResilience: Math.max(0, Number(event.target.value) || 0) })} className={fieldStyle} /></Field><Field label="Técnica máxima relacionada"><Input value={domain.maximumTechnique} onChange={event => update({ maximumTechnique: event.target.value })} placeholder="Opcional" className={fieldStyle} /></Field></div></section>
    <section className="rounded-2xl border border-violet-300/12 bg-[#120c1d]/85 p-4 sm:p-5"><div className="flex items-center gap-3 border-b border-violet-300/10 pb-4"><span className="grid h-7 w-7 place-items-center rounded-full border border-violet-300/25 bg-violet-300/[.06] text-xs font-semibold text-violet-100">3</span><div><h3 className="font-display text-xl text-stone-100">Efeito e contrajogo</h3><p className="mt-1 text-sm text-stone-500">Explique o que a expansão faz e como a cena ainda permite reação ou resistência.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Efeito, área e duração"><Textarea value={domain.effect} onChange={event => update({ effect: event.target.value })} placeholder="Descreva o efeito da expansão" className={`${fieldStyle} min-h-32`} /></Field><Field label="Resistência, reação ou contrajogo"><Textarea value={domain.counterplay} onChange={event => update({ counterplay: event.target.value })} placeholder="Descreva como a expansão pode ser enfrentada" className={`${fieldStyle} min-h-32`} /></Field></div></section>
    <section className="rounded-2xl border border-amber-300/15 bg-amber-300/[.03] p-4 sm:p-5"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full border border-amber-300/25 bg-amber-300/[.06] text-xs font-semibold text-amber-100">4</span><div><h3 className="font-display text-xl text-amber-100">Estado de mesa</h3><p className="mt-1 text-sm text-stone-400">Aprovação e acerto garantido permanecem declarações explícitas e auditáveis.</p></div></div><div className="mt-4 flex flex-col gap-3 rounded-xl border border-amber-300/15 bg-black/20 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-5"><label className="flex cursor-pointer items-center gap-2 text-sm text-stone-200"><input type="checkbox" className="accent-amber-300" checked={domain.guaranteedHit} onChange={event => update({ guaranteedHit: event.target.checked })} />Acerto garantido declarado</label><label className="flex cursor-pointer items-center gap-2 text-sm text-stone-200"><input type="checkbox" className="accent-amber-300" checked={domain.approved} onChange={event => update({ approved: event.target.checked })} />Mestre aprovou a expansão</label></div><span className="inline-flex items-center gap-2 text-xs text-amber-100"><CheckCircle2 className="h-4 w-4" />Disponível a partir do nível {domain.requiredLevel}</span></div><EditableObservation className="mt-4" entityType="domain" entityId="domain-expansion" value={domain.notes} canEdit onSave={notes => { update({ notes }); onDiary("Observação de Domínio atualizada", notes || "A observação do Domínio foi removida.", "note"); }} placeholder="Registre decisões de mesa, riscos ou detalhes narrativos deste Domínio." /></section></div>;
}
